### ISSUE TITLE
No Transfer Ownership Pattern

### ISSUE THREAD

**Issue by trungore** [LodestarFinance/lodestar-token-fix#3]
### Title
No Transfer Ownership Pattern
### Affected smart contract
https://github.com/LodestarFinance/lodestar-token-fix/blob/main/contracts/TokenFIx.sol#L47-L52
### Description
The current admin transfer process involves the current admin calling `_setAdmin()`.
This function doesn't check the new admin is not the zero address and proceeds to write the new admin's address into the admin's state variable.
If the nominated EOA account is not a valid account, it is entirely possible the owner may accidentally transfer ownership to an uncontrolled account, breaking all functions with the onlyAdmin() modifier.
### Recommendation 
Implement a two step process where the admin nominates an account and the nominated account needs to call an acceptAdmin() function for the transfer of admin to fully succeed. This ensures the nominated EOA account is a valid and active account.

**Comment by LodestarFinance** [comment]
This is known behavior
